import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetbrains = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const FontImport = () => (
  <style>{`
    @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&family=Inter:wght@400;500;600&display=swap');

    .font-display { font-family: 'JetBrains Mono', monospace; }
    .font-body { font-family: 'Inter', sans-serif; }
    .font-mono { font-family: 'JetBrains Mono', monospace; }

    .bg-paper { background-color: #F5F6F5; }
    .bg-ink { background-color: #1B222C; }
    .text-ink { color: #1B222C; }
    .text-added { color: #1F8A45; }
    .text-removed { color: #C23B3B; }
    .bg-added { background-color: #1F8A45; }
    .text-accent-blue { color: #2563C7; }
    .bg-accent-blue { background-color: #2563C7; }
    .border-accent-blue { border-color: #2563C7; }
    .text-muted-slate { color: #5B6472; }

    .terminal-dot { width: 10px; height: 10px; border-radius: 50%; }
  `}</style>
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jetbrains.variable} ${inter.variable} h-full antialiased`}>
      <FontImport />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
